### PR TITLE
Integrated ContextualBalloon.

### LINKED ISSUE #55: ContextualBalloon integration
See: https://github.com/ckeditor/ckeditor5-ui/issues/134

### PR DESCRIPTION
**Pull request by oskarwrobel**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Feature: Integrated `ContextualBalloon` with `ClassicEditorUI`. Closes #55.

---

Depends on: https://github.com/ckeditor/ckeditor5-ui/pull/177

### CODE REVIEW

**Comment by oskarwrobel** [comment]
This should be more generic than `ClassicEditorUi`. A few features which can be used not only with classic editor will depend on it (Link, Image) so this should land to total generic UI controller. Looks like we need `EditorUi` class?
//cc @Reinmar @oleq

**Comment by oleq** [comment]
I'm not so sure about having it in EditorUI or any other underlying class. There could be dozens of editor implementations using them and none of them having anything to do with the balloons so creating such dependency and running this code would be pointless.

I'm more for creating an utility. I guess it should be called by Link or Image and it would inject the `ContextualBalloon` controller into `editor.ui` if not already inserted. WDYT?

**Comment by oskarwrobel** [comment]
> There could be dozens of editor implementations using them and none of them having anything to do with the balloons so creating such dependency and running this code would be pointless.

It makes sense for me but OTOH `EditorUIView` creates `body` collection in a similar way. It's always created.

**Comment by oleq** [comment]
What if we implemented this util as a `Plugin`? If Link or Image requires this plugin to work, it injects the balloon into `editor.ui`.

**Comment by oskarwrobel** [comment]
I was thinking about the same. I'm wondering where we can place such a plugin?

**Comment by oleq** [comment]
I think ckeditor5-ui feels like the right place.

**Comment by oskarwrobel** [comment]
This will make `ckeditor5-ui` dependent on `ckeditor5-core`.

**Comment by oskarwrobel** [comment]
It's already dependend https://github.com/ckeditor/ckeditor5-ui/blob/master/package.json#L14

**Comment by oleq** [comment]
This is funny but I can't locate any real dependency despite the entry in `package.json` maybe it's a leftover after some refac?

**Comment by oskarwrobel** [comment]
I'm closing this PR because plugin will handle it.

**Pull request closed without merging**
